/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aswajaclothes.grid;

import aswajaclothes.connection.ConnectionManager;
import aswajaclothes.model.master.CustomerModel;
import aswajaclothes.model.master.EkspedisiModel;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Satrio
 */
public class EkspedisiGridFrame extends javax.swing.JFrame implements MouseListener {

    /**
     * Creates new form CustomerGridFrame
     */
    public EkspedisiGridFrame() {
        initComponents();
        initEkspedisi();
        initTableListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEkspedisi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Data Ekspedisi");

        tblEkspedisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Alamat", "No Telepon"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblEkspedisi.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblEkspedisi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initEkspedisi() {
        String[] ekspedisiColumn = new String [] { "Kode", "Nama"};
        ArrayList<String[]> ekspedisisRow = new ArrayList<>();
        listEkspedisi = new ConnectionManager().getEkspedisis();
        for (EkspedisiModel ekspedisi : listEkspedisi) {
            String[] rowData = new String[]{
                ekspedisi.getKode(),
                ekspedisi.getName(),
            };
            ekspedisisRow.add(rowData);
        }
        TableModel tblModel = new DefaultTableModel(ekspedisisRow.toArray(new String[][]{}), ekspedisiColumn){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblEkspedisi.setModel(tblModel);
    }
    
    private void initTableListener(){
        tblEkspedisi.addMouseListener(this);
    }
    
    // Variables declaration - able to modify
    private ArrayList<EkspedisiModel> listEkspedisi;
    private GridListener listener;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEkspedisi;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        int rowSelected = tblEkspedisi.getSelectedRow();
        EkspedisiModel ekspedisi = listEkspedisi.get(rowSelected);
        listener.onSelectedRow(ekspedisi, EkspedisiGridFrame.class.getSimpleName());
        dispose();
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }
    
    public void setGridListener(GridListener listener){
        this.listener = listener;
    }
    
}
